# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build pokemon-stuff`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t pokemon-stuff`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system pokemon-stuff && \
          adduser --system -G pokemon-stuff pokemon-stuff

COPY dist/pokemon-stuff pokemon-stuff/
RUN chown -R pokemon-stuff:pokemon-stuff .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix pokemon-stuff --omit=dev -f install

CMD [ "node", "pokemon-stuff" ]
